---
title: "Validatierapport"
author: "Els Lommelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, include=FALSE}
library(dplyr)
library(dhcurve)
library(knitr)

```

```{r, warning=FALSE, results='asis', include=FALSE}

#sortering maken volgens aandeel outliers in curve

#curves met enkel gevlagde outliers verwijderen

Uitvoer <- NULL

for (Poutliers in unique(Selectie$maxResid)) {
  SelectieOutliers <- Selectie %>%
    filter(maxResid == Poutliers)
  for (Boomsoort in unique(SelectieOutliers$BMS)) {
    SelectieSoort <- SelectieOutliers %>%
      filter(BMS == Boomsoort)
    for (Domein in unique(SelectieSoort$DOMEIN_ID)) {
      SelectieModel <- SelectieSoort %>%
        filter(DOMEIN_ID == Domein)
      #print(unique(SelectieModel$Reden))  #nolint
      #print(maakGrafiek(SelectieModel))  #nolint
      if (TypeRapport == "dynamisch") {
        Uitvoer <- c(Uitvoer, knit_child("DomeincurveDynamisch.Rmd"))
      } else {
        Uitvoer <- c(Uitvoer, knit_child("Domeincurve.Rmd"))
      }
    }
  }
}
  

```

```{r output, results='asis'}

cat(Uitvoer, sep = "\n")
```

