on:
  push:
    branches:
      - main
  schedule:
    - cron: '6 0 * * 1'

name: "check lintr"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check lintr"
    steps:
      - uses: inbo/actions/lint_pkg@main
